# Generated by Django 2.0.1 on 2018-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='execution_output',
            field=models.TextField(default=None),
        ),
    ]
