# Generated by Django 2.0.1 on 2018-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_crash_execution_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
